[package]
name = "libtw2-register"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"
rust-version = "1.63.0"

[dependencies]
bitflags = "2.10.0"
libtw2-packer = { path = "../packer/" }
libtw2-polyfill-1-63 = { path = "../polyfill-1-63/" }
libtw2-serverbrowse = { path = "../serverbrowse/" }
log = "0.4.28"
reqwest = "0.12.9"
serde = { version = "1.0.228", features = ["rc"] }
serde_derive = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.38.2", features = ["macros", "time"] }
uuid = { version = "1.18.1", features = ["v4"] }
