[package]
name = "libtw2-tools"
version = "0.0.1"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.6"
buffer = "0.1.9"
chrono = { version = "0.4.42", features = ["serde"] }
clap = { version = "4.5.51", features = ["deprecated"] }
csv = "1.4.0"
hexdump = "0.1.2"
itertools = "0.14.0"
libtw2-common = { path = "../common/" }
libtw2-datafile = { path = "../datafile/" }
libtw2-demo = { path = "../demo/" }
libtw2-gamenet-ddnet = { path = "../gamenet/ddnet/" }
libtw2-gamenet-spec = { path = "../gamenet/spec/" }
libtw2-gamenet-teeworlds-0-6 = { path = "../gamenet/teeworlds-0.6/" }
libtw2-gamenet-teeworlds-0-7 = { path = "../gamenet/teeworlds-0.7/" }
libtw2-logger = { path = "../logger/" }
libtw2-map = { path = "../map/" }
libtw2-net = { path = "../net/" }
libtw2-packer = { path = "../packer/", features = ["uuid"] }
libtw2-serverbrowse = { path = "../serverbrowse/" }
libtw2-snapshot = { path = "../snapshot/" }
libtw2-teehistorian = { path = "../teehistorian/" }
libtw2-world = { path = "../world/" }
log = "0.4.28"
rmp = "0.8.14"
serde = "1.0.228"
serde_derive = "1.0.228"
serde_json = "1.0.145"
uuid = { version = "1.18.1", features = ["serde"] }
vec_map = "0.8.2"
void = "1.0.2"
walkdir = "2.5.0"
warn = "0.2.2"
